
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Jul 04 16:40:38 CDT 2021
//----------------------------------------------------

package Principal;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Scanner = 9;
  public static final int Op_relacional = 20;
  public static final int Parentesis_Cierre = 25;
  public static final int S_linea = 12;
  public static final int Op_booleano = 23;
  public static final int If = 4;
  public static final int T_dato = 33;
  public static final int Else = 5;
  public static final int While = 7;
  public static final int Division = 18;
  public static final int Cadena = 32;
  public static final int For = 8;
  public static final int EOF = 0;
  public static final int P_coma = 30;
  public static final int Llave_Apertura = 26;
  public static final int Llave_Cierre = 27;
  public static final int error = 1;
  public static final int Parentesis_Apertura = 24;
  public static final int Op_atribucion = 21;
  public static final int Print = 10;
  public static final int ERROR = 35;
  public static final int Do = 6;
  public static final int Op_logico = 19;
  public static final int Public = 2;
  public static final int Identificador = 31;
  public static final int Resta = 16;
  public static final int Print_ln = 11;
  public static final int Multiplicacion = 17;
  public static final int Op_incremento = 22;
  public static final int Numero = 34;
  public static final int Suma = 15;
  public static final int Main = 3;
  public static final int Igual = 14;
  public static final int Corchete_Apertura = 28;
  public static final int Corchete_Cierre = 29;
  public static final int Comillas = 13;
}

